<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIAiAbzh\srcApp_KernelNvDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIAiAbzh/srcApp_KernelNvDebugContainer.php') {
    touch(__DIR__.'/ContainerIAiAbzh.legacy');

    return;
}

if (!\class_exists(srcApp_KernelNvDebugContainer::class, false)) {
    \class_alias(\ContainerIAiAbzh\srcApp_KernelNvDebugContainer::class, srcApp_KernelNvDebugContainer::class, false);
}

return new \ContainerIAiAbzh\srcApp_KernelNvDebugContainer([
    'container.build_hash' => 'IAiAbzh',
    'container.build_id' => '1e755eff',
    'container.build_time' => 1576512038,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIAiAbzh');
