<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.E6MDrq1' shared service.

return $this->privates['.service_locator.E6MDrq1'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'App\\Controller\\MainController::list' => ['privates', '.service_locator.AXMvmOr', 'get_ServiceLocator_AXMvmOrService.php', true],
    'App\\Controller\\MainController::question' => ['privates', '.service_locator.0ymjLr.', 'get_ServiceLocator_0ymjLr_Service.php', true],
    'App\\Controller\\MainController:list' => ['privates', '.service_locator.AXMvmOr', 'get_ServiceLocator_AXMvmOrService.php', true],
    'App\\Controller\\MainController:question' => ['privates', '.service_locator.0ymjLr.', 'get_ServiceLocator_0ymjLr_Service.php', true],
], [
    'App\\Controller\\MainController::list' => '?',
    'App\\Controller\\MainController::question' => '?',
    'App\\Controller\\MainController:list' => '?',
    'App\\Controller\\MainController:question' => '?',
]);
